### ISSUE TITLE
xacars_config date

### ISSUE THREAD

**Issue by xpd259** [magicflyer/Zumeweb.Pacific.V1#2]
Hello, I love your theme 
but I'm unable to find the xacars_config data page
I see there is a template for it xacars_config.tpl
sorry if I'm just missing it

**Comment by magicflyer** [comment]
Hey Thomas,

The way phpVMS works is that it will look for a default template file in /core/templates first before lib/skins. So if you don’t find something in lib/skins it’s that nothing has been modified from it, therefore phpVMS would use, by default, the one in /core/templates.

Regards,
Ryan Herga

**Comment by xpd259** [comment]
ah, I see sorry I'm still very new to phpVMS 
I was just expecting a download link 
many thanks for the quick reply :+1:
